// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jZ0gNFSyvT6TzauuzXvyd695gQnPS7g',
    appId: '1:869633080972:web:9e4366cd6162c4dbddc5a9',
    messagingSenderId: '869633080972',
    projectId: 'chat-guru-e9b44',
    authDomain: 'chat-guru-e9b44.firebaseapp.com',
    storageBucket: 'chat-guru-e9b44.appspot.com',
    measurementId: 'G-5XYG8V2004',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7DTsGjpvyAzn9g8hePc7kaCaeFCUlOQ',
    appId: '1:869633080972:android:1ef8836fb187f45bddc5a9',
    messagingSenderId: '869633080972',
    projectId: 'chat-guru-e9b44',
    storageBucket: 'chat-guru-e9b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqg2q-_d6fX31QGVGRtl1I0UV708xSf_w',
    appId: '1:869633080972:ios:743be44465a7e315ddc5a9',
    messagingSenderId: '869633080972',
    projectId: 'chat-guru-e9b44',
    storageBucket: 'chat-guru-e9b44.appspot.com',
    iosBundleId: 'com.example.chatguru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqg2q-_d6fX31QGVGRtl1I0UV708xSf_w',
    appId: '1:869633080972:ios:743be44465a7e315ddc5a9',
    messagingSenderId: '869633080972',
    projectId: 'chat-guru-e9b44',
    storageBucket: 'chat-guru-e9b44.appspot.com',
    iosBundleId: 'com.example.chatguru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9jZ0gNFSyvT6TzauuzXvyd695gQnPS7g',
    appId: '1:869633080972:web:443dbf5e124bdc63ddc5a9',
    messagingSenderId: '869633080972',
    projectId: 'chat-guru-e9b44',
    authDomain: 'chat-guru-e9b44.firebaseapp.com',
    storageBucket: 'chat-guru-e9b44.appspot.com',
    measurementId: 'G-BD5QRGW200',
  );
}
